\documentclass{article}
\usepackage{subcaption}
\usepackage{booktabs}
% \setkeys{Gin}{width=1\textwidth}
% \setkeys{Gin}{height=1\textheight}
\begin{document}

<<label = Table1.1,echo=FALSE, results='asis'>>=
load("/Volumes/untitled/PTC.RData")

source("/Users/andrewwallace/DissertationPublications/DegreeBandDescTable.R")

@




Ok. I finally got this to work. But it involves running the ENTIRE data set up 
file because objects in the global enviroment are not in the scope of the local
environment of the knitr R code chunk (unknown if multiple chunks in the same 
knitr document have the same scope) for reproducibility purposes. This works, but 
it is EXTREMELY inefficient. The solution may be to save the data to an Rdata file
and read that. 

Done. It worked SO much faster. , out.extra='angle=90' 
% 
% \begin{figure}{t}
% \centering
% 
% <<echo=FALSE, message = FALSE, out.extra='angle=90'>>=
% library(TraMineR)
% load("/Volumes/untitled/PTC.BA1.RData")
% load("/Volumes/untitled/PTC.BA2.RData")
% load("/Volumes/untitled/PTC.AA1.RData")
% load("/Volumes/untitled/PTC.AA2.RData")
% source("/Users/andrewwallace/DissertationPublications/CreateStateSeqObj.R")
% source("/Users/andrewwallace/DissertationPublications/CreateTopTwentyFiguresBA1.R")
% @
%   \caption{Top Twenty Sequences, BA1}
%   \label{fig:Top20BA1}
%   \end{figure}
%   
% 	\begin{figure}[t]
%   \centering
% <<echo=FALSE, message = FALSE>>=
% library(TraMineR)
% load("/Volumes/untitled/PTC.BA1.RData")
% load("/Volumes/untitled/PTC.BA2.RData")
% load("/Volumes/untitled/PTC.AA1.RData")
% load("/Volumes/untitled/PTC.AA2.RData")
% source("/Users/andrewwallace/DissertationPublications/CreateStateSeqObj.R")
% source("/Users/andrewwallace/DissertationPublications/CreateTopTwentyFiguresBA2.R")
% @
% 		\caption{BA2}
%     \caption{Top Twenty Sequences, BA2}
% 	\end{figure}
% 
% 
% 
% \newpage
% 
% Why is this not working
% 
% 
\end{document}